### ISSUE TITLE
Include smallDevTools website for code sharing

### ISSUE THREAD

**Issue by twf-nikhila** [shlomif/how-to-share-code-online#4]
Hey Shlomi,

Thank you for writing this detailed guide, **very helpful**.

Please add this tool smallDevTools for easy one-click code sharing of codes with syntax highlight & title option.

https://smalldev.tools/share-bin

**Comment by shlomif** [comment]
Hi @twf-nikhila ! I'm glad you like my guide. However, do note that there are too many paste sites for us to list them all. One issue I ran into with yours is that the submit button didn't work when https://noscript.net/ was active.

What do you think?

**Comment by shlomif** [comment]
Closing due to lack of reply.
